# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('TWIN', 'Twin'), ('FULL', 'Full'), ('QUEEN', 'Queen'), ('KING', 'King')], max_length=5)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.BigIntegerField()),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMERICANEXPRESS', 'American Express'), ('DISCOVER', 'Discover')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=25)),
                ('phone_num', models.CharField(max_length=12)),
                ('theme', models.CharField(max_length=20)),
                ('distance', models.SmallIntegerField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.SmallIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_people', models.SmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ManyToManyField(to='disney.Customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('room_view', models.CharField(max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('COMP_SHUTTLE', 'Complimentary Shuttle'), ('SHUTTLE_FEE', 'Shuttle (Additional Fee)'), ('NONE', 'None')], max_length=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Room'),
        ),
        migrations.AddField(
            model_name='rate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Room'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Restaurant'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Customer'),
        ),
        migrations.AddField(
            model_name='bed',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Room'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disney.Hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='transportation',
            unique_together=set([('hotel', 'trans_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('hotel', 'room_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('hotel', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('hotel', 'room', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('customer', 'phone_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('customer', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together=set([('restaurant', 'dish_name', 'size')]),
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together=set([('customer', 'card_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together=set([('hotel', 'room', 'size')]),
        ),
        migrations.AlterUniqueTogether(
            name='amenity',
            unique_together=set([('hotel', 'amenity_type')]),
        ),
    ]
