# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('GIFT_SHOP', 'Gift Shop'), ('FIT_CENTER', 'Fitness Center'), ('LAUNDRY', 'Laundromat'), ('WIFI', 'Wi-Fi'), ('POOL', 'Swimming Pool'), ('TICKETS', 'Disneyland Ticket Desk'), ('ROOM_SERV', 'Room Service')], max_length=25),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
