# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney', '0002_auto_20161204_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
