# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney', '0003_auto_20161204_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
